#!/bin/bash
#
# Example server script.
# This runs as ROOT by default. Drop privileges.
#
# Do any additional server setup here. Perms are pre-setup for steam:steam
# unless you explicitly change anything. Docker environment variables are
# available.


# Finally, launch the dedicated server under the steam user.
# This will run wine (for windows servers) and launch the server.
su steam -c  "xvfb-run \
  --auto-servernum \
  wine ${SERVER_DIR}/ConanSandboxServer.exe -log -nosteam"

# This will launch a standard linux dedicated server.
su steam -c "/data/server/startserver.sh \
  -configfile=/data/server/serverconfig.xml"
